int32 KEY_NONE=0
int32 KEY_A_UP=1
int32 KEY_A_DOWN=2
int32 KEY_B_UP=3
int32 KEY_B_DOWN=4
int32 KEY_C_UP=5
int32 KEY_C_DOWN=6
int32 KEY_D_UP=7
int32 KEY_D_DOWN=8
int32 KEY_E_UP=9
int32 KEY_E_MID=10
int32 KEY_E_DOWN=11
int32 KEY_F_UP=12
int32 KEY_F_MID=13
int32 KEY_F_DOWN=14
int32 KEY_G_LEFT=15
int32 KEY_G_MID=16
int32 KEY_G_RIGHT=17
int32 KEY_H_LEFT=18
int32 KEY_H_MID=19
int32 KEY_H_RIGHT=20

std_msgs/Header header

int32 key_event_new
int32 key_event_old

int8 button_a
int8 button_b
int8 button_c
int8 button_d
int8 button_e
int8 button_f
int8 button_g
int8 button_h

float32 x1
float32 y1
float32 x2
float32 y2
